import {
  Allergies,
  Arm,
  BackPain,
  Baby0203m,
  Bandaged,
  Biopsy,
  BloodPressure,
  BloodPressure2,
  Body,
  Boy0105y,
  Cane,
  Cardiogram,
  Cast,
  ChildCare,
  ColdChain,
  Crutches,
  DentalHygiene,
  Elderly,
  Exercise,
  ExerciseYoga,
  Foot,
  Head,
  Heart,
  Heartbeat,
  HeartCardiogram,
  HeartOrgan,
  Joints,
  Leg,
  Microscope,
  Nutrition,
  Odontology,
  OdontologyImplant,
  Orthotics,
  PhysicalTherapy,
  Running,
  SkinCancer,
  Sling,
  Spine,
  Stent,
  Syringe,
  SyringeVaccine,
  Tooth,
  Traumatism,
  Travel,
  UltrasoundScanner,
  VirusShield,
  Walking,
  Weights,
  Wheelchair,
} from "healthicons-react/outline";

/** Health Icons map — use for specialized medical/therapy illustrations. */
export const HEALTH_ICONS = {
  allergies: Allergies,
  arm: Arm,
  backPain: BackPain,
  baby: Baby0203m,
  bandaged: Bandaged,
  biopsy: Biopsy,
  bloodPressure: BloodPressure,
  bloodPressure2: BloodPressure2,
  body: Body,
  boy: Boy0105y,
  cane: Cane,
  cardiogram: Cardiogram,
  cast: Cast,
  childCare:   ChildCare,
  coldChain: ColdChain,
  crutches: Crutches,
  dentalHygiene: DentalHygiene,
  elderly: Elderly,
  exercise: Exercise,
  exerciseYoga: ExerciseYoga,
  foot: Foot,
  head: Head,
  heart: Heart,
  heartbeat: Heartbeat,
  heartCardiogram: HeartCardiogram,
  heartOrgan: HeartOrgan,
  joints: Joints,
  leg: Leg,
  microscope: Microscope,
  nutrition: Nutrition,
  odontology: Odontology,
  odontologyImplant: OdontologyImplant,
  orthotics: Orthotics,
  physicalTherapy: PhysicalTherapy,
  running: Running,
  skinCancer: SkinCancer,
  sling: Sling,
  spine: Spine,
  stent: Stent,
  syringe: Syringe,
  syringeVaccine: SyringeVaccine,
  tooth: Tooth,
  traumatism: Traumatism,
  travel: Travel,
  ultrasound: UltrasoundScanner,
  virusShield: VirusShield,
  walking: Walking,
  weights: Weights,
  wheelchair: Wheelchair,
};

export function getHealthIcon(key) {
  return HEALTH_ICONS[key] ?? null;
}
